# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Celestine
  module Docs
    module B_SPEC_REFERENCE
      # # Filters, Gradients & Visual Effects
      #
      # Celestine provides first-class support for declarative SVG filter pipelines, color gradients,
      # patterns, and SMIL animations. This guide covers how to construct complex graphical effects
      # in pure Crystal.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Filter Pipelines & fe* Primitives</strong></td>
      #       <td><code>.topic_01_filter_primitives</code></td>
      #       <td>Constructing multi-stage filter pipelines using feGaussianBlur, feColorMatrix, and more.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Gradients & Patterns</strong></td>
      #       <td><code>.topic_02_gradients_and_patterns</code></td>
      #       <td>Configuring smooth color transitions and repeating visual fills.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Declarative SMIL Animations</strong></td>
      #       <td><code>.topic_03_smil_animations</code></td>
      #       <td>Animating attributes, transforms, and motion paths without JavaScript.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/effects/filter.cr
      # - src/effects/filters/
      # - src/effects/gradients/
      # - src/effects/animation/
      #
      module FILTERS_AND_EFFECTS
        # **Filter Pipelines & fe* Primitives**: Constructing multi-stage filter pipelines using feGaussianBlur, feColorMatrix, and more.
        #
        # Celestine implements 16 W3C filter primitives under `Celestine::Filter`. Filters are declared
        # using `ctx.filter` (automatically placed into `<defs>`) and assigned to shapes using `.set_filter(id)`.
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Primitive</th>
        #       <th>Celestine Method</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>`feGaussianBlur`</td>
        #       <td>`f.blur`</td>
        #       <td>Standard Gaussian blur with stdDeviation</td>
        #     </tr>
        #     <tr>
        #       <td>`feColorMatrix`</td>
        #       <td>`f.color_matrix`</td>
        #       <td>Matrix, saturate, hueRotate, luminanceToAlpha</td>
        #     </tr>
        #     <tr>
        #       <td>`feDropShadow`</td>
        #       <td>`f.drop_shadow`</td>
        #       <td>Combined blur and offset drop shadow</td>
        #     </tr>
        #     <tr>
        #       <td>`feDisplacementMap`</td>
        #       <td>`f.displacement_map`</td>
        #       <td>Geometric distortion using map channels</td>
        #     </tr>
        #     <tr>
        #       <td>`feTurbulence`</td>
        #       <td>`f.turbulence`</td>
        #       <td>Perlin noise and fractal noise generation</td>
        #     </tr>
        #     <tr>
        #       <td>`feBlend`</td>
        #       <td>`f.blend`</td>
        #       <td>Blend modes (multiply, screen, overlay, etc.)</td>
        #     </tr>
        #     <tr>
        #       <td>`feComposite`</td>
        #       <td>`f.composite`</td>
        #       <td>Porter-Duff compositing operators</td>
        #     </tr>
        #     <tr>
        #       <td>`feComponentTransfer`</td>
        #       <td>`f.component_transfer`</td>
        #       <td>Linear, gamma, and table color curves</td>
        #     </tr>
        #     <tr>
        #       <td>`feMorphology`</td>
        #       <td>`f.morphology`</td>
        #       <td>Erode and dilate operators</td>
        #     </tr>
        #     <tr>
        #       <td>`feOffset`</td>
        #       <td>`f.offset`</td>
        #       <td>Spatial translation of graphic buffers</td>
        #     </tr>
        #     <tr>
        #       <td>`feTile`</td>
        #       <td>`f.tile`</td>
        #       <td>Repeats input image to fill filter region</td>
        #     </tr>
        #     <tr>
        #       <td>`feFlood`</td>
        #       <td>`f.flood`</td>
        #       <td>Solid color flood fill</td>
        #     </tr>
        #     <tr>
        #       <td>`feSpecularLighting`</td>
        #       <td>`f.specular_lighting`</td>
        #       <td>Surface lighting bump-mapping</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```crystal
        # svg = Celestine.draw do |ctx|
        #   ctx.filter do |f|
        #     f.id = "soft-glow"
        #     f.blur do |b|
        #       b.input = Celestine::Filter::SOURCE_GRAPHIC
        #       b.std_deviation = 5
        #       b.result = "blur-out"
        #     end
        #     f.merge do |m|
        #       m.add_node("blur-out")
        #       m.add_node(Celestine::Filter::SOURCE_GRAPHIC)
        #     end
        #   end
        #
        #   ctx.circle do |c|
        #     c.x = 100
        #     c.y = 100
        #     c.radius = 40
        #     c.fill = "#00f0ff"
        #     c.set_filter("soft-glow")
        #   end
        # end
        # ```
        #
        def self.topic_01_filter_primitives : Nil; end

        # **Gradients & Patterns**: Configuring smooth color transitions and repeating visual fills.
        #
        # Gradients define smooth color transitions across shapes. Celestine supports both linear and radial
        # gradients, which can be bound directly via `shape.set_fill(gradient)`.
        #
        # #### Working Examples
        #
        # ```crystal
        # svg = Celestine.draw do |ctx|
        #   grad = ctx.linear_gradient do |g|
        #     g.id = "sunset"
        #     g.stop(0, color: "#ff512f")
        #     g.stop(1, color: "#dd2476")
        #   end
        #
        #   ctx.rectangle do |r|
        #     r.width = 200
        #     r.height = 100
        #     r.set_fill(grad)
        #   end
        # end
        # ```
        #
        def self.topic_02_gradients_and_patterns : Nil; end

        # **Declarative SMIL Animations**: Animating attributes, transforms, and motion paths without JavaScript.
        #
        # Every drawable can host SMIL animation tags:
        # - `shape.animate`: Animates attributes like `opacity`, `fill`, `r`, `width`.
        # - `shape.animate_motion`: Moves shapes along arbitrary SVG path trajectories.
        # - `shape.animate_transform_*`: Hardware-accelerated rotations, scaling, and translations.
        #
        def self.topic_03_smil_animations : Nil; end
      end
    end
  end
end
{% end %}
