# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Celestine
  module Docs
    module B_SPEC_REFERENCE
      # # SVG Elements & Spec Checklist
      #
      # Celestine aims for high-fidelity compliance with W3C SVG 1.1 and SVG 2 specifications.
      # This reference catalogues all standard SVG elements, their implementation status in Celestine,
      # and their corresponding Crystal classes and DSL methods.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Element Parity & Status Matrix</strong></td>
      #       <td><code>.topic_01_element_checklist</code></td>
      #       <td>Element-by-element status table showing implemented, planned, and out-of-scope tags.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Supported Presentation Attributes</strong></td>
      #       <td><code>.topic_02_presentation_attributes</code></td>
      #       <td>Styling and geometric presentation attributes available across drawables.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/drawables/
      # - src/effects/
      # - src/modules/
      #
      module SVG_ELEMENTS
        # **Element Parity & Status Matrix**: Element-by-element status table showing implemented, planned, and out-of-scope tags.
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Status</th>
        #       <th>SVG Tag</th>
        #       <th>Celestine Class</th>
        #       <th>DSL Helper</th>
        #       <th>Notes</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<a>`</td>
        #       <td>`Celestine::Anchor`</td>
        #       <td>`ctx.anchor`</td>
        #       <td>Hyperlink container</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<animate>`</td>
        #       <td>`Celestine::Animate`</td>
        #       <td>`shape.animate`</td>
        #       <td>SMIL attribute animation</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<animateMotion>`</td>
        #       <td>`Celestine::Animate::Motion`</td>
        #       <td>`shape.animate_motion`</td>
        #       <td>Motion path animation</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<animateTransform>`</td>
        #       <td>`Celestine::Animate::Transform::*`</td>
        #       <td>`shape.animate_transform_*`</td>
        #       <td>Rotate, scale, translate, skew</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<circle>`</td>
        #       <td>`Celestine::Circle`</td>
        #       <td>`ctx.circle`</td>
        #       <td>cx, cy, r, diameter</td>
        #     </tr>
        #     <tr>
        #       <td>^</td>
        #       <td>`<clipPath>`</td>
        #       <td>Planned</td>
        #       <td>`ctx.clip_path`</td>
        #       <td>Vector path clipping</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<defs>`</td>
        #       <td>Handled implicitly</td>
        #       <td>`ctx.define` / `define: true`</td>
        #       <td>Collected into `<defs>` buffer</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<ellipse>`</td>
        #       <td>`Celestine::Ellipse`</td>
        #       <td>`ctx.ellipse`</td>
        #       <td>cx, cy, rx, ry</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<g>`</td>
        #       <td>`Celestine::Group`</td>
        #       <td>`ctx.group`</td>
        #       <td>Structural grouping container</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<image>`</td>
        #       <td>`Celestine::Image`</td>
        #       <td>`ctx.image`</td>
        #       <td>Bitmap/vector image embed</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<line>`</td>
        #       <td>`Celestine::Line`</td>
        #       <td>`ctx.line`</td>
        #       <td>x1, y1, x2, y2</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<linearGradient>`</td>
        #       <td>`Celestine::Gradient::Linear`</td>
        #       <td>`ctx.linear_gradient`</td>
        #       <td>Linear color transitions</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<marker>`</td>
        #       <td>`Celestine::Marker`</td>
        #       <td>`ctx.marker`</td>
        #       <td>Arrowheads and path markers</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<mask>`</td>
        #       <td>`Celestine::Mask`</td>
        #       <td>`ctx.mask`</td>
        #       <td>Alpha & luminance masking</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<path>`</td>
        #       <td>`Celestine::Path`</td>
        #       <td>`ctx.path`</td>
        #       <td>Full SVG 1.1 path command support</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<pattern>`</td>
        #       <td>`Celestine::Pattern`</td>
        #       <td>`ctx.pattern`</td>
        #       <td>Repeated visual tile patterns</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<polygon>`</td>
        #       <td>`Celestine::Polygon`</td>
        #       <td>`ctx.polygon`</td>
        #       <td>Closed multi-point shapes</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<polyline>`</td>
        #       <td>`Celestine::Polyline`</td>
        #       <td>`ctx.polyline`</td>
        #       <td>Open multi-point stroke lines</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<radialGradient>`</td>
        #       <td>`Celestine::Gradient::Radial`</td>
        #       <td>`ctx.radial_gradient`</td>
        #       <td>Radial color transitions</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<rect>`</td>
        #       <td>`Celestine::Rectangle`</td>
        #       <td>`ctx.rectangle`</td>
        #       <td>x, y, width, height, rx, ry</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<stop>`</td>
        #       <td>`Celestine::Gradient::Stop`</td>
        #       <td>`grad.stop`</td>
        #       <td>Gradient color stops</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<svg>`</td>
        #       <td>`Celestine::Svg`</td>
        #       <td>`Celestine.draw`</td>
        #       <td>Document root & nested viewports</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<text>`</td>
        #       <td>`Celestine::Text`</td>
        #       <td>`ctx.text`</td>
        #       <td>Typography & layout attributes</td>
        #     </tr>
        #     <tr>
        #       <td>✓</td>
        #       <td>`<use>`</td>
        #       <td>`Celestine::Use`</td>
        #       <td>`ctx.use`</td>
        #       <td>Reusable element instantiator</td>
        #     </tr>
        #     <tr>
        #       <td>^</td>
        #       <td>`<symbol>`</td>
        #       <td>Planned</td>
        #       <td>`ctx.symbol`</td>
        #       <td>Reusable icon symbols with viewBox</td>
        #     </tr>
        #     <tr>
        #       <td>^</td>
        #       <td>`<tspan>`</td>
        #       <td>Planned</td>
        #       <td>`text.tspan`</td>
        #       <td>Inline sub-string text styling</td>
        #     </tr>
        #     <tr>
        #       <td>^</td>
        #       <td>`<textPath>`</td>
        #       <td>Planned</td>
        #       <td>`text.text_path`</td>
        #       <td>Text aligned along curved path</td>
        #     </tr>
        #     <tr>
        #       <td>^</td>
        #       <td>`<style>`</td>
        #       <td>Planned</td>
        #       <td>`ctx.style`</td>
        #       <td>Embedded CSS stylesheet block</td>
        #     </tr>
        #     <tr>
        #       <td>✘</td>
        #       <td>`<foreignObject>`</td>
        #       <td>Planned</td>
        #       <td>`ctx.foreign_object`</td>
        #       <td>Embedding HTML inside SVG</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        def self.topic_01_element_checklist : Nil; end

        # **Supported Presentation Attributes**: Styling and geometric presentation attributes available across drawables.
        #
        # Through `Celestine::Modules::StrokeFill`, `Position`, and `Transform`, drawables support:
        #
        # - **Stroke & Fill**: `stroke`, `fill`, `stroke_width`, `fill_opacity`, `stroke_opacity`, `opacity`
        # - **Dashes & Caps**: `dash_array`, `dash_offset`, `line_join`, `line_cap`, `miter_limit`
        # - **Rendering Hints**: `shape_rendering`, `vector_effect`, `color_interpolation`, `fill_rule`
        # - **Transforms**: `translate(x, y)`, `scale(x, y)`, `rotate(deg, ox, oy)`, `skew_x(deg)`, `skew_y(deg)`, `matrix(a,b,c,d,e,f)`
        # - **Effects Binding**: `set_filter(id)`, `set_mask(id)`, `set_marker_start(id)`, `set_fill(gradient)`
        #
        def self.topic_02_presentation_attributes : Nil; end
      end
    end
  end
end
{% end %}
