site_name: Celestine
site_url: https://docs.celestine.dev/
repo_url: https://github.com/celestinecr/celestine
edit_uri: blob/master/docs/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

extra_css:
  - css/mkdocstrings.css

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      watch: [src]
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.superfences
  - deduplicate-toc
  - meta
  - toc:
      permalink: "#"
