# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Celestine
  module Docs
    module A_GETTING_STARTED
      # # Getting Started & System Overview
      #
      # Celestine is a fast, pure-Crystal library for programmatic SVG generation.
      # It provides both a fluent builder DSL and a strongly-typed object model for
      # creating, transforming, styling, and animating SVG graphics.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Introduction & Architecture</strong></td>
      #       <td><code>.topic_01_introduction</code></td>
      #       <td>Core concepts and structural layout of Celestine.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/celestine.cr
      # - src/drawables/
      # - src/effects/
      #
      module OVERVIEW
        # **Introduction & Architecture**: Core concepts and structural layout of Celestine.
        #
        # Celestine organizes SVG generation around three pillars:
        #
        # 1. **Drawables**: Core SVG elements such as `<svg>`, `<rect>`, `<circle>`, `<ellipse>`, `<line>`, `<polygon>`, `<polyline>`, `<path>`, `<text>`, `<image>`, and `<use>`.
        # 2. **Containers & Definitions**: `<g>`, `<a>`, `<defs>`, `<mask>`, `<marker>`, `<pattern>`, `<linearGradient>`, and `<radialGradient>`.
        # 3. **Effects & Animations**: Declarative SVG filters (`<filter>`, `<feGaussianBlur>`, etc.) and SMIL animations (`<animate>`, `<animateMotion>`, `<animateTransform>`).
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Component</th>
        #       <th>Module / Directory</th>
        #       <th>Role</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>Root DSL</td>
        #       <td>`Celestine.draw`</td>
        #       <td>Builder entrypoint yielding `Celestine::Svg`</td>
        #     </tr>
        #     <tr>
        #       <td>Drawables</td>
        #       <td>`src/drawables/`</td>
        #       <td>Concrete SVG tag implementations inheriting `Celestine::Drawable`</td>
        #     </tr>
        #     <tr>
        #       <td>Effects</td>
        #       <td>`src/effects/`</td>
        #       <td>Gradients, filters, masks, markers, patterns, animations</td>
        #     </tr>
        #     <tr>
        #       <td>Math</td>
        #       <td>`src/math/`</td>
        #       <td>`Point`, `FPoint`, and coordinate manipulation</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```crystal
        # require "celestine"
        #
        # svg = Celestine.draw do |ctx|
        #   ctx.view_box = {x: 0, y: 0, w: 200, h: 200}
        #   ctx.rectangle do |r|
        #     r.x = 10
        #     r.y = 10
        #     r.width = 180
        #     r.height = 180
        #     r.fill = "blue"
        #     r.radius_x = 8
        #     r.radius_y = 8
        #   end
        # end
        #
        # puts svg
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Never forget to set view_box or width/height on the root SVG for proper scaling.
        # - **Warning**: Remember that units default to pixels if none are specified.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: How do I stream SVG directly to an IO instead of allocating a String?**
        #   A: Call Celestine.draw(io) { |ctx| ... } to render directly to any IO object.
        #
        # - **Q: Can I use Celestine without the DSL block syntax?**
        #   A: Yes! Every drawable and effect is a standard Crystal class (e.g. Celestine::Rectangle.new) that can be instantiated and appended to any container.
        #
        def self.topic_01_introduction : Nil; end
      end
    end
  end
end
{% end %}
