# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Celestine
  module Docs
    module C_DSL_AND_CREATIVE
      # # Fluent Path Builders, Procedural Shapes & Turtle Graphics
      #
      # Celestine provides a fluent, chainable SVG path construction API alongside
      # procedural shape generators and an intuitive turtle graphics engine.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Fluent Path Construction</strong></td>
      #       <td><code>.topic_01_fluent_paths</code></td>
      #       <td>Chainable movement, lines, curves, and arcs with Point and Tuple overloads.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Procedural Shape Generators</strong></td>
      #       <td><code>.topic_02_procedural_shapes</code></td>
      #       <td>Instantly build stars, regular polygons, annular arc sectors, rounded rects, and hearts.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Turtle Graphics</strong></td>
      #       <td><code>.topic_03_turtle_graphics</code></td>
      #       <td>Relative angle and distance path generation.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/drawables/path.cr
      #
      module FLUENT_PATHS_AND_SHAPES
        # **Fluent Path Construction**: Chainable movement, lines, curves, and arcs with Point and Tuple overloads.
        #
        # Rather than relying solely on cryptic SVG command codes, `Celestine::Path` supports
        # fluent chaining where every command returns `self`.
        #
        # Supported commands include:
        # - `move_to(x, y)` / `move_to(point)` / `move_by(dx, dy)`
        # - `line_to(x, y)` / `line_to(point)` / `line_by(dx, dy)`
        # - `horizontal_to(x)` / `vertical_to(y)`
        # - `curve_to(c1x, c1y, c2x, c2y, x, y)` / `smooth_curve_to(...)`
        # - `quad_to(cx, cy, x, y)` / `smooth_quad_to(...)`
        # - `arc_to(rx, ry, rotation, large, sweep, x, y)` / `arc_by(...)`
        # - `close` or `close_path`
        #
        # #### Working Examples
        #
        # ```crystal
        # Celestine.draw do |ctx|
        #   ctx.path do |p|
        #     p.stroke = "#0284c7"
        #     p.fill = "none"
        #     p.move_to(10, 20)
        #      .line_to(100, 20)
        #      .curve_to(120, 20, 150, 50, 150, 80)
        #      .close
        #   end
        # end
        # ```
        #
        def self.topic_01_fluent_paths : Nil; end

        # **Procedural Shape Generators**: Instantly build stars, regular polygons, annular arc sectors, rounded rects, and hearts.
        #
        # Paths can procedurally generate complex vector geometries in a single call:
        #
        # - `regular_polygon(cx, cy, sides, radius)`
        # - `star(cx, cy, points, outer_radius, inner_radius)`
        # - `arc_sector(cx, cy, r_inner, r_outer, start_angle, end_angle)`
        # - `rounded_rect(x, y, width, height, rx, ry)`
        # - `heart(cx, cy, size)`
        #
        # #### Working Examples
        #
        # ```crystal
        # Celestine.draw do |ctx|
        #   ctx.path do |p|
        #     p.fill = "#f59e0b"
        #     p.star(cx: 100, cy: 100, points: 5, outer_radius: 50, inner_radius: 25)
        #   end
        # end
        # ```
        #
        def self.topic_02_procedural_shapes : Nil; end

        # **Turtle Graphics**: Relative angle and distance path generation.
        #
        # Use the integrated `turtle` engine to draw algorithmic geometries using relative forward
        # steps and angle turns.
        #
        # #### Working Examples
        #
        # ```crystal
        # Celestine.draw do |ctx|
        #   ctx.path do |p|
        #     p.stroke = "#10b981"
        #     p.turtle(start_x: 100, start_y: 100) do |t|
        #       4.times do
        #         t.forward(80)
        #          .turn_right(90)
        #       end
        #       t.close
        #     end
        #   end
        # end
        # ```
        #
        def self.topic_03_turtle_graphics : Nil; end
      end
    end
  end
end
{% end %}
