# ==============================================================================
# Celestine::Docs Documentation System - Master Index & Navigation Hub
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# ==============================================================================

{% unless flag?(:release) %}
module Celestine
  # The `Celestine::Docs` module is the authoritative technical reference and documentation guide.
  #
  # ## Learning Tracks & Topic Index
  #
  # The documentation is paced into 2 distinct tracks:
  #
  # ### 1. Getting started (`A_GETTING_STARTED`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>OVERVIEW</code></td>
  #       <td><strong>Getting Started & System Overview</strong></td>
  #       <td>Introduction to Celestine SVG generation DSL and object model.</td>
  #     </tr>
  #     <tr>
  #       <td><code>USAGE_GUIDE</code></td>
  #       <td><strong>Quickstart & Usage Guide</strong></td>
  #       <td>Comprehensive guide to drawing, DSL blocks, object models, and element reuse in Celestine.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 2. Spec reference (`B_SPEC_REFERENCE`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>SVG_ELEMENTS</code></td>
  #       <td><strong>SVG Elements & Spec Checklist</strong></td>
  #       <td>Comprehensive audit of SVG elements, current implementation status, and DSL method mappings.</td>
  #     </tr>
  #     <tr>
  #       <td><code>FILTERS_AND_EFFECTS</code></td>
  #       <td><strong>Filters, Gradients & Visual Effects</strong></td>
  #       <td>Reference guide for SVG filter primitives, linear and radial gradients, masks, and SMIL animations.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  module Docs
    # **Quick-Start Commands**: Essential commands for building, running, and testing.
    #
    # #### Docs Commands:
    # ```bash
    # shards install
    # crystal spec
    # crystal docs
    # ```
    def self.topic_01_quick_start : Nil; end

    # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced.
    #
    # #### Structured Learning Tracks
    #
    # ##### 1. Getting started (`A_GETTING_STARTED`)
    # - `A_GETTING_STARTED::OVERVIEW`: **Getting Started & System Overview** &mdash; Introduction to Celestine SVG generation DSL and object model.
    # - `A_GETTING_STARTED::USAGE_GUIDE`: **Quickstart & Usage Guide** &mdash; Comprehensive guide to drawing, DSL blocks, object models, and element reuse in Celestine.
    #
    # ##### 2. Spec reference (`B_SPEC_REFERENCE`)
    # - `B_SPEC_REFERENCE::SVG_ELEMENTS`: **SVG Elements & Spec Checklist** &mdash; Comprehensive audit of SVG elements, current implementation status, and DSL method mappings.
    # - `B_SPEC_REFERENCE::FILTERS_AND_EFFECTS`: **Filters, Gradients & Visual Effects** &mdash; Reference guide for SVG filter primitives, linear and radial gradients, masks, and SMIL animations.
    #
    def self.topic_02_reading_paths : Nil; end

    # **Master Table of Contents**: Complete hierarchical topic index.
    #
    # #### Complete Documentation Index
    #
    # ##### `A_GETTING_STARTED`
    # - `A_GETTING_STARTED::OVERVIEW`: **Getting Started & System Overview** &mdash; Introduction to Celestine SVG generation DSL and object model.
    # - `A_GETTING_STARTED::USAGE_GUIDE`: **Quickstart & Usage Guide** &mdash; Comprehensive guide to drawing, DSL blocks, object models, and element reuse in Celestine.
    #
    # ##### `B_SPEC_REFERENCE`
    # - `B_SPEC_REFERENCE::SVG_ELEMENTS`: **SVG Elements & Spec Checklist** &mdash; Comprehensive audit of SVG elements, current implementation status, and DSL method mappings.
    # - `B_SPEC_REFERENCE::FILTERS_AND_EFFECTS`: **Filters, Gradients & Visual Effects** &mdash; Reference guide for SVG filter primitives, linear and radial gradients, masks, and SMIL animations.
    #
    def self.topic_03_table_of_contents : Nil; end

    # :nodoc:
    def self.quick_start : Nil; topic_01_quick_start; end
    # :nodoc:
    def self.reading_paths : Nil; topic_02_reading_paths; end
    # :nodoc:
    def self.table_of_contents : Nil; topic_03_table_of_contents; end
  end
end

require "./docs/a_getting_started/overview"
require "./docs/a_getting_started/usage_guide"
require "./docs/b_spec_reference/svg_elements"
require "./docs/b_spec_reference/filters_and_effects"
{% end %}
