# ==============================================================================
# Celestine::Docs Documentation System - Master Index & Navigation Hub
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# ==============================================================================

{% unless flag?(:release) %}
module Celestine
  # The `Celestine::Docs` module is the authoritative technical reference and documentation guide.
  #
  # ## Learning Tracks & Topic Index
  #
  # The documentation is paced into 1 distinct tracks:
  #
  # ### 1. Getting started (`A_GETTING_STARTED`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>OVERVIEW</code></td>
  #       <td><strong>Getting Started & System Overview</strong></td>
  #       <td>Introduction to Celestine SVG generation DSL and object model.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  module Docs
    # **Quick-Start Commands**: Essential commands for building, running, and testing.
    #
    # #### Docs Commands:
    # ```bash
    # shards install
    # crystal spec
    # crystal docs
    # ```
    def self.topic_01_quick_start : Nil; end

    # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced.
    #
    # #### Structured Learning Tracks
    #
    # ##### 1. Getting started (`A_GETTING_STARTED`)
    # - `A_GETTING_STARTED::OVERVIEW`: **Getting Started & System Overview** &mdash; Introduction to Celestine SVG generation DSL and object model.
    #
    def self.topic_02_reading_paths : Nil; end

    # **Master Table of Contents**: Complete hierarchical topic index.
    #
    # #### Complete Documentation Index
    #
    # ##### `A_GETTING_STARTED`
    # - `A_GETTING_STARTED::OVERVIEW`: **Getting Started & System Overview** &mdash; Introduction to Celestine SVG generation DSL and object model.
    #
    def self.topic_03_table_of_contents : Nil; end

    # :nodoc:
    def self.quick_start : Nil; topic_01_quick_start; end
    # :nodoc:
    def self.reading_paths : Nil; topic_02_reading_paths; end
    # :nodoc:
    def self.table_of_contents : Nil; topic_03_table_of_contents; end
  end
end

require "./docs/a_getting_started/overview"
{% end %}
