name: Crystal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: shards install
    - name: Run specs
      run: crystal spec
    - name: Build targets
      run: |
        shards build logo
        shards build benchmark
