name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Build docs
      run: crystal docs
    - name: Fix CNAME
        run: echo 'docs.celestine.dev' > CNAME
    - name: Deploy docs
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
